exchange:
  exchange_name: standx
  private_key: ""
  chain: bsc

symbol: BTC-USD

grid:
  upper_price: 200000
  lower_price: 60000
  price_step: 5
  grid_count: 5
  price_spread: 50
  order_quantity: 0.0001
  sleep_interval: 1
